blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/WVFNWEvuqX
    about: Report an issue on our official Discord!
  - name: SpigotMC Thread
    url: https://www.spigotmc.org/threads/mobchip-entity-ai-wrapper-pathfinders-controllers-and-more.556441/
    about: Read about MobChip!
  - name: JitPack CI
    url: https://jitci.com/gh/GamerCoder215/MobChip
    about: View MobChip's Build Information.